---
- hosts: "{{ hosts }}"
  remote_user: root
  become: yes
  gather_facts: no
  serial: 1
  vars:
    base_path: "/opt/openhex/nomo"
    ansible_ssh_private_key_file: "./identity_files/{{ inventory_hostname }}/key.pem"
  tasks:
  - name: mkdir logs dir
    file: path={{ base_path }}/logs state=directory owner=root group=root mode=0755
  - name: mkdir bin dir
    file: path={{ base_path }}/bin state=directory owner=root group=root mode=0755
  - name: mkdir conf dir
    file: path={{ base_path }}/conf state=directory owner=root group=root mode=0755

  - name: sync output
    synchronize: src=../output/ dest={{ base_path}}/
  
#- name: copy binary
#  copy: src=../output/bin/nomo dest={{ base_path }}/bin/nomo owner=root group=root mode=0755 backup=yes
#- name: copy env
#  template: src=../output/bin/.env dest={{ base_path }}/bin/.env owner=root group=root mode=0755
#- name: copy systemd services
#  template: src=openhex.nomo.service dest={{ base_path }}/openhex.nomo.service owner=root group=root mode=0755
#- name: copy run.sh
#  template: src=run.sh dest={{ base_path }}/run.sh owner=root group=root mode=0755
    
  - name: enable systemd
    shell: systemctl enable {{ base_path }}/openhex.nomo.service
  - name: restart agent
    shell: systemctl restart openhex.nomo.service

# - name: stop
#   shell: systemctl stop openhex.nomo{{env}}.service
# - name: disable
#   shell: systemctl disable {{ base_path }}/openhex.nomo.service
